INSERT INTO `locations` (`city`, `locality`, `id`) VALUES
('Tunis', 'Agence de Menzah', 1),
('Tunis', 'Agence de Tunis', 3),
('Tunis', 'Agence de Bardo', 4),
('Tunis', 'Agence de Marsa', 5),
('Sfax', 'Agence de Mahres ', 6),
('Sfax', 'Agence de Sakiet El-Daer', 11),
('Sfax', 'Agence de Sakiet Ezzit', 12),
('Sfax', 'Agence de Skhira', 13),
('Sfax', 'Agence de Al-Hanasha', 14),
('Sfax', 'Agence de Bir Ali bin Khalifa', 15),
('Sousse', 'Agence de Akoda', 21),
('Sousse', 'Agence de Enfidha ', 22),
('Sousse', 'Agence de Hergla', 23),
('Sousse', 'Agence de Bouficha', 24),
('Sousse', 'Agence de Msaken', 25),
('Utique', 'Agence de Utique', 26),
('Bizerte', 'Agence de Zarzouna', 27),
('Bizerte', 'Agence de Bizerte', 28),
('Bizerte',  'Agence de Mater', 29),
('Bizerte',   'Agence de Manzel Jmil', 30),
('Ben Arous', 'Agence de Mhamdia ', 31),
('Ben Arous', 'Agence de Mourouj ', 32),
('Ben Arous', 'Agence de Boumhal', 33),
('Ben Arous', 'Agence de Fouchena ', 34),
('Ben Arous', 'Agence de Rades', 35)
